baseURL = "https://sketchnoting.dev/"
languageCode = "en-us"
title = "sketchnoting.dev"
theme = "hugo-creative-portfolio-theme"
publishDir = "docs"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "violet"
  description = "sketchnoting.dev: Tech Talks Sketchnotes"
  copyright = "&copy;2019"
  sidebarAbout = [
    "We are <a href=\"https://twitter.com/lariki/\">Lara Martín</a> and <a href=\"https://twitter.com/MiBLT\">Miguel Beltran</a>, two passionate sketchnoters with the goal of sharing knowledge via visual note-taking.",
    "In this site, you will find all our past sketchnotes, from newest to olderst.",
  ]

  # Nav links in the side bar
  # [[params.navlinks]]
  # name = "Home"
  # url = "sketchnotes/"
  # home = true

  # [[params.navlinks]]
  # name = "About"
  # url = "about/"

  [params.social]
  # email         = "email@example.com"
  # twitter       = "full profile url in twitter"
  # youtube       = "full profile url in youtube"
